### ISSUE TITLE
Add Shop-System

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/GRAD-On-The-Fly#10]
Allow vehicle selection blufor
allow some defenses for opfor

**Comment by y0014984** [comment]
The current way the vehicle is teleported is not synced between clients. We should spawn a flag and attach a shop to spawn a vehicle.

**Comment by y0014984** [comment]
Now Blufor and Opfor have a shop. Blufor and Opfor commander spawn with a wallet of 5000$. The shops are attached to the Opfor barrel and the blufor flag. An addational action allows to check current balance. Both shops contain the default rifle (250$) and 3 different magazine types for that rifle (10$). Blufor shop also contains an M2-Technical (2000$), a Truck (1000$) and an Helicopter (3000$) Vehicles spawn 15 meters to the north of the flag in a height of 1 meter. If the terrain is very steep this won't work. Rifles and ammunition can only be bought if there is enough space in players inventory.

Buying defenses is another topic.

**Comment by y0014984** [comment]
Now opfor shop has 3 sizes of sandbag barriers and anti-vehicle-mines. Additonally, both sides have grenades and smoke.

Done.
