### ISSUE TITLE
Mark Opfor Spawn better 

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/GRAD-On-The-Fly#11]
make radius of blufor spawn more apparent

**Comment by y0014984** [comment]
WIP. I'm already able to draw a circle on the map. Basically it's a circle image file, that is colored and translucent in the engine. This is added to the map. That's the way the line elements in vanilla are drawn on the map. Like for the lines this has to be updated every time someone opens the map and zooms in and out or translates to other map positions. Hopefully done tomorrow.

**Comment by nomisum** [comment]
oh my no native circles? what a shame lol

but if it works it works

**Comment by y0014984** [comment]
> oh my no native circles?

There are no native cicles.

**Comment by y0014984** [comment]
Done, see Screenshot. Draw an 1000 meters red circle including a Flag symbol marking the barrel position. BLUFOR can't spawn inside of the circle.

<img width="533" alt="image" src="https://github.com/gruppe-adler/GRAD-On-The-Fly/assets/50139270/372ecd36-caa2-4f04-95ad-7a76f4fd502a">
