### ISSUE TITLE
Give Opfor Time to drag barrel

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/GRAD-On-The-Fly#14]
- make Barrel carryable as inventory item
- give Barrel interaction to end this ability and declare Opfor Spawn complete

**Comment by y0014984** [comment]
Opfor needs to be restricted in moving the barrel. Otherwise they run away with it.

**Comment by nomisum** [comment]
just remove the action after opfor declares its phase to be over

**Comment by y0014984** [comment]
Ok. This would work but then we need to resync the marker position, if they moved for example 500m away with it.

**Comment by y0014984** [comment]
Done.
