### ISSUE TITLE
Phases dont switch automatically yet

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/GRAD-On-The-Fly#5]
manually doing it by GM works though

**Comment by nomisum** [comment]
should be fixed in https://github.com/gruppe-adler/GRAD-On-The-Fly/commit/619b1199b0b8b1ff3d2fb4c166fb778679fb04e2

**Comment by y0014984** [comment]
Overhauled the automatic phase switching. GM interaction is only needed once at start to switch from GAMEMASTER to OPFOR.
