### ISSUE TITLE
invisible players phenomenon

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/GRAD-On-The-Fly#8]
maybe related to GM + teleport combination

* GM always sees every player
* GM as player does not see every player, probably not teleported ones while in GM interface

**Comment by y0014984** [comment]
Cannot reproduce. As GM I can always see all teleported players, no matter if I am in the GM Interface or not.

**Comment by y0014984** [comment]
Seems to be fixed. No such issues in the event on 2023-12-04
